# Generated by Django 3.2.20 on 2023-08-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20230824_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
